version: '3.3'
volumes:
  pg_data:
  static:
  media:
services:
  db:
    image: postgres:15
    env_file:
      - ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data  
  backend:
    image: smirnovds/foodgram_backend
    env_file:
      - ./.env
    volumes:
      - static:/backend_static
      - media:/media/
    depends_on:
      - db
  frontend:
    env_file:
      - ./.env
    image: smirnovds/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
  nginx:
    image: smirnovds/foodgram_nginx
    env_file:
      - ./.env
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles
      - media:/media