# Generated by Django 4.2.5 on 2023-09-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(editable=False, null=True, verbose_name='Подписки'),
        ),
    ]
